### ISSUE TITLE
Logout (mit eIAM Account) funktioniert nicht

### ISSUE THREAD

**Issue by flenny** [swisstopo/swissgeol-boreholes-suite#1162]
**Steps to reproduce**
1. Go to '[dev-boreholes.swissgeol.ch](https://dev-boreholes.swissgeol.ch/)'
2. Login with an **eIAM** user account
3. Agree to the 'Disclaimer' pop-up
4. Logout

**Expected behavior**
The user gets logged-out. The log-in screen to log in again shows up.

**Current behavior**
The user immediately gets logged-in again.

**Tasks**
- [ ] Logout Beschreibungstext anpassen (? Logout from swissgeol ?)
- [x] SAML Logout Binding (für DEV/INT) anpassen
- [x] Fallback OIDC Logout mit [extraQueryParams](https://authts.github.io/oidc-client-ts/interfaces/SignoutRequestArgs.html#extraQueryParams) implementieren

**Comment by flenny** [comment]
Die Problematik wurde heute Donnerstagmorgen kurz mit @TIL-EBP und @danjov thematisiert.

Boreholes (und auch Assets) sind beides Applikationen bei denen ein Login und entsprechende Berechtigungen zwingend vorausgesetzt sind. Es gibt keine Programmbestandteile die öffentlich zugänglich sind. Deshalb wird beim Aufruf der Seite (bspw. [int-boreholes.swissgeol.ch](https://int-boreholes.swissgeol.ch/)) automatisch zum eIAM Login weitergeleitet. Ist der Benutzer im eIAM bereits angemeldet - bspw. weil die Anmeldung bereits für einen andere Applikation erfolgt ist - wird der Benutzer automatisch und ohne ein Anmeldeformular angezeigt zu bekommen, zurück zur Boreholes Applikation geleitet und angemeldet.

Die Frage die sich nun stellt ist folgende: Was ist das gewünschte Verhalten, wenn sich ein Benutzer in Boreholes abmeldet?
Im Moment ist das verhalten so, dass nach der Abmeldung in Boreholes automatisch wieder zum eIAM Login weiterleitet wird. Da der Benutzer im eIAM bereits eingeloggt ist erfolgt automatisch die Weiterleitung zu Boreholes. Der Benutzer ist wieder eingeloggt. Der Logout hat somit "keine" wirkliche Funktionalität.

Eine weitere Variante wäre, dass der Benutzer beim Logout (in Boreholes) im eIAM gleich komplett abmeldet würde. Dies hätte zur Folge, dass der Benutzer auch in allen anderen Applikationen die das eIAM Login verwenden (bswp. assets, viewer, boreholes, etc) abgemeldet wird und ein erneuter Login (mit 2FA/Smartcard) nötig wird um diese Applikationen erneut zu verwenden. Dieser Prozess (SAML Logout Request) ist von Cognito grundsätzlich [unterstützt](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-saml-idp-sign-out.html). Irgendwo hakt es aber noch in der Umsetzung. Hier müsste der Fehler allenfalls geimeinsam mit dem BIT analysiert und behoben werden.

**Comment by flenny** [comment]
Wenn die Amazon Cognito Logout URL direkt aufgerufen wird, scheint der Logout (auch im eIAM) zu klappen.
`https://ngm-prod.auth.eu-west-1.amazoncognito.com/logout?client_id=3ulg46i2dkilah403hluf6hoi7&logout_uri=https%3A%2F%2Fboreholes.swissgeol.ch`

**Comment by flenny** [comment]
Im Client scheints beim Aufruf (Logout Request) noch einen Fehler zu geben.
![image](https://github.com/geoadmin/suite-bdms/assets/1365121/66d91d5c-670c-4bbf-afab-4010c18733e5)

Der Aufruf des vom OIDC Standard abweichenden Cognito [Logout Endpoints](https://docs.aws.amazon.com/cognito/latest/developerguide/logout-endpoint.html) wahrscheinlich besser via `extraQueryParams` im [SignoutRequest](https://authts.github.io/oidc-client-ts/interfaces/SignoutRequestArgs.html)-Objekt implementieren. Vgl. [hier](https://github.com/geoadmin/suite-bdms/blob/b008ce217a150698e2bf4cad7dc321499b536a3a/src/client/src/commons/auth/CognitoLogoutHandler.js#L17).

**Comment by flenny** [comment]
Aufgrund der Tatsache, dass pro Umgebung unterschiedliche Accounts existieren (bspw. Fed-Login, CH Login, etc) und diese in den verschiedenen Applikationen auch unterschiedlich verwendet werden können, macht ein explizites Ausloggen aus der eIAM Umgebung definitiv sinn. Zum besseren Verständnis müsste "Logout" wahrscheinlich in etwas wie "Logout from swissgeol" umbenannt werden. Dann ist klar, dass auch aus den anderen "swissgeol" Applikationen (assets, viewer) ausgeloggt wird.

**Comment by flenny** [comment]
Es ist soeben aufgefallen, dass das Binding der Logout URL in der vom BIT für REF und ABN zur Verfügung gestellten SAML Metadatendokument (metadata.xml) von der PROD Konfiguration leicht abweicht.
```
# PROD
<md:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="...

# REF & ABN
<md:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="...
```
Das Binding für die DEV/REF und INT/ABN Umgebung wurde entsprechend der PROD Konfiguration angepasst. Ein Test ist noch ausstehend.

**Comment by RBordoni** [comment]
Aus Weekly swisstopo 16.04.2024: Logout umbenennen zu “Logout from swissgeol”

**Comment by danjov** [comment]
@mPfifi hat das Logout applikationsübergreifend getestet und ein Logout-Problem auf der PROD-Umgebung festgestellt:
> Ich habe wie gestern besprochen den Logout aus den aktuellen Versionen von boreholes.swissgeol.ch und int-assets.swissgeol.ch (beide mit Login über eIAM) und dessen Auswirkung auf andere eIAM-Applikationen wie FileTransferService des BIT, SuccessFactors oder ActaNova einmal getestet. Der Logout aus boreholes (PROD) oder assets (INT) beeinflusst die anderen Applikationen nicht, man bleibt dort eingeloggt und kann weiter arbeiten. Daneben habe ich dabei aber festgestellt, dass
der Logout aus boreholes PROD nicht funktioniert. Man gerät in eine Schlaufe und wird direkt wieder eingeloggt, ein Logout scheint nicht möglich zu sein.
der Logout bei assets INT wie erwartet funktioniert und man wieder auf die eIAM-Seite mit der Auswahl Login-Verfahren kommt.

**Comment by flenny** [comment]
Das Problem mit dem nicht funktionierenden Logout wurde mit https://github.com/swisstopo/swissgeol-boreholes-suite/pull/1173 behoben. Die Installation auf Prod hat aber noch nicht stattgefunden, weshalb dort der Test noch feschlägt. Ein Update der Prod Umgebung wird für heute Freitag eingeplant.
